const actions = { 
 LOGIN: 'LOGIN',
 LOGIN_FAILED: 'LOGIN_FAILED',
 LOGIN_SUCCESS: 'LOGIN_SUCCESS',
 STUDENT_DETAILS_FETCH_SUCCESS: 'STUDENT_DETAILS_FETCH_SUCCESS',
 STUDENT_DETAILS_FETCH_FAILED: 'STUDENT_DETAILS_FETCH_FAILED',
 GET_STUDENT_LIST: 'GET_STUDENT_LIST',
 OPEN_STUDENT_MODAL: 'OPEN_STUDENT_MODAL',
 CLOSE_STUDENT_MODAL: 'CLOSE_STUDENT_MODAL',
 FILTER_STUDENT_LIST: 'FILTER_STUDENT_LIST',
 TOGGLE_ETTENDANCE_STATUS: 'TOGGLE_ETTENDANCE_STATUS',
 ATTENDANCE_STATUS_CHANGED: 'ATTENDANCE_STATUS_CHANGED'
};
export default actions;